name: install node modules

inputs:
  root:      { required: true,  type: string }
  cache:     { required: false, type: string, default: yes }
  cache_gen: { required: false, type: string, default: v1 }

runs:
  using: "composite"
  steps:

    - name: node info
      id: node-info
      shell: bash
      run: |
        case "${{ inputs.cache }}" in
          yes|workflow) cache="${{ inputs.cache }}" ;;
          *) cache= ;;
        esac
        gen="${{ input.cache_gen }}"
        node -v
        hashfiles="${{ hashFiles(inputs.root+'/**/package-lock.json') }}"
        hash="$( uname -mrsv | md5sum | awk '{print $1}' )"-"$gen"-"$hashfiles"
        [ "$cache" == 'workflow' ] && hash=$hash-${{ github.run_id }}
        cat << END
        ::set-output name=cache::$cache
        ::set-output name=hash::$hash
        END

    - name: cache node_modules
      if: steps.apt.outpts.cache != ''
      uses: actions/cache@v2
      with:
        path: ${{ inputs.root }}/*/node_modules
        key: ${{ steps.node-info.outputs.hash }}

    - name: configure node modules
      shell: bash
      run: |
        for lock in $(find ${{ inputs.root }} -name package-lock.json)
        do
          dir=$(dirname $lock)
          if [ -d $dir/node_modules ]
          then
            echo "skip $dir"
          else
            echo "configure $dir"
            (cd $dir && npm install)
          fi
        done
