name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          root: __test__
      - run: node __test__/hello
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          root: __test__
      - run: node __test__/hello
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
  no-root:
    needs: cached
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
      - run: node __test__/hello
      - run: echo "cache-hit=\"${{ steps.action.outputs.cache-hit }}\""
  no-cache:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: no
          root: __test__
      - run: node __test__/hello
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  cache-gen:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          root: __test__
          cache_gen: v2
      - run: node __test__/hello
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
