name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cache: workflow
          root: __test__
      - run: node __test__/hello
  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cache: workflow
          root: __test__
      - run: node __test__/hello
  no-root:
    needs: cached
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cache: workflow
      - run: node __test__/hello
  no-cache:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cache: no
          root: __test__
      - run: node __test__/hello
  cache-gen:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cache: workflow
          root: __test__
          cache_gen: v2
      - run: node __test__/hello
